In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import os

In [4]:
pwd

'/home/braincreator'

In [6]:
#Capturing File Path
iowa_data = pd.read_csv('/home/braincreator/iowa/train.csv')

In [7]:
iowa_data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [8]:
#Selecting Prediction target and assigning it to y
#Since I am trying to predict house prices, I will pull 'SalePrice' from the columns as the prediction target variable

y = iowa_data.SalePrice

In [9]:
#To create model, I will choose and input features
#Inputted features will include variables that can be focused upon to determine home prices

iowa_features = ['LotArea', 'Utilities', 'YearBuilt', 'YearRemodAdd', '1stFlrSF', '2ndFlrSF', 'BedroomAbvGr', 'KitchenAbvGr',
                 'TotRmsAbvGrd', 'Fireplaces', 'GarageArea', 'PavedDrive', 'PoolArea']

In [10]:
#I will now correspond the data in iowa to that of iowa features and assign it to X

X = iowa_data[iowa_features]

In [11]:
X.describe()

,LotArea,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageArea,PoolArea
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,10516.828082,1971.267808,1984.865753,1162.626712,346.992466,2.866438,1.046575,6.517808,0.613014,472.980137,2.758904
std,9981.264932,30.202904,20.645407,386.587738,436.528436,0.815778,0.220338,1.625393,0.644666,213.804841,40.177307
min,1300.000000,1872.000000,1950.000000,334.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000
25%,7553.500000,1954.000000,1967.000000,882.000000,0.000000,2.000000,1.000000,5.000000,0.000000,334.500000,0.000000
50%,9478.500000,1973.000000,1994.000000,1087.000000,0.000000,3.000000,1.000000,6.000000,1.000000,480.000000,0.000000
75%,11601.500000,2000.000000,2004.000000,1391.250000,728.000000,3.000000,1.000000,7.000000,1.000000,576.000000,0.000000
max,215245.000000,2010.000000,2010.000000,4692.000000,2065.000000,8.000000,3.000000,14.000000,3.000000,1418.000000,738.000000

In [12]:
X.head(9)

,LotArea,Utilities,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageArea,PavedDrive,PoolArea
0,8450,AllPub,2003,2003,856,854,3,1,8,0,548,Y,0
1,9600,AllPub,1976,1976,1262,0,3,1,6,1,460,Y,0
2,11250,AllPub,2001,2002,920,866,3,1,6,1,608,Y,0
3,9550,AllPub,1915,1970,961,756,3,1,7,1,642,Y,0
4,14260,AllPub,2000,2000,1145,1053,4,1,9,1,836,Y,0
5,14115,AllPub,1993,1995,796,566,1,1,5,0,480,Y,0
6,10084,AllPub,2004,2005,1694,0,3,1,7,1,636,Y,0
7,10382,AllPub,1973,1973,1107,983,3,1,7,2,484,Y,0
8,6120,AllPub,1931,1950,1022,752,2,2,8,2,468,Y,0

In [13]:
#By looking at certain data, it can be easily seen that some features are redundant 
#I will remove Utilities, PavedDrive, and PoolArea as features

iowa_features = ['LotArea', 'YearBuilt', 'YearRemodAdd', '1stFlrSF', '2ndFlrSF', 'BedroomAbvGr', 'KitchenAbvGr',
                 'TotRmsAbvGrd', 'Fireplaces', 'GarageArea']

In [14]:
#I will correspond the data just like I did before, assigning it to Z

Z = iowa_data[iowa_features]

In [15]:
Z.describe()

,LotArea,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageArea
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,10516.828082,1971.267808,1984.865753,1162.626712,346.992466,2.866438,1.046575,6.517808,0.613014,472.980137
std,9981.264932,30.202904,20.645407,386.587738,436.528436,0.815778,0.220338,1.625393,0.644666,213.804841
min,1300.000000,1872.000000,1950.000000,334.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
25%,7553.500000,1954.000000,1967.000000,882.000000,0.000000,2.000000,1.000000,5.000000,0.000000,334.500000
50%,9478.500000,1973.000000,1994.000000,1087.000000,0.000000,3.000000,1.000000,6.000000,1.000000,480.000000
75%,11601.500000,2000.000000,2004.000000,1391.250000,728.000000,3.000000,1.000000,7.000000,1.000000,576.000000
max,215245.000000,2010.000000,2010.000000,4692.000000,2065.000000,8.000000,3.000000,14.000000,3.000000,1418.000000

In [16]:
Z.head(9)

,LotArea,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageArea
0,8450,2003,2003,856,854,3,1,8,0,548
1,9600,1976,1976,1262,0,3,1,6,1,460
2,11250,2001,2002,920,866,3,1,6,1,608
3,9550,1915,1970,961,756,3,1,7,1,642
4,14260,2000,2000,1145,1053,4,1,9,1,836
5,14115,1993,1995,796,566,1,1,5,0,480
6,10084,2004,2005,1694,0,3,1,7,1,636
7,10382,1973,1973,1107,983,3,1,7,2,484
8,6120,1931,1950,1022,752,2,2,8,2,468

In [17]:
#The model I will use is a Decision Tree Regressor to specified parameters of a random state of 1
#The steps I will now follow are to: Define, Fit, Create Predictions, Validate, Evaluate, and Redesign - if need be.

from sklearn.tree import DecisionTreeRegressor as DTR

In [18]:
#Defining model

iowa_model = DTR(random_state = 1)

In [19]:
#Fit model

iowa_model.fit(Z,y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=1, splitter='best')

In [20]:
#Create Predictions 

predictions = iowa_model.predict(Z.head(1460))
print ('Making predictions for the following 1,460 houses:')
print (Z.head(1460))
print ('The predictions are:')
print (iowa_model.predict(Z.head(1460)))

Making predictions for the following 1,460 houses:
      LotArea  YearBuilt  YearRemodAdd  1stFlrSF  2ndFlrSF  BedroomAbvGr  \
0        8450       2003          2003       856       854             3
1        9600       1976          1976      1262         0             3
2       11250       2001          2002       920       866             3
3        9550       1915          1970       961       756             3
4       14260       2000          2000      1145      1053             4
...       ...        ...           ...       ...       ...           ...
1455     7917       1999          2000       953       694             3
1456    13175       1978          1988      2073         0             3
1457     9042       1941          2006      1188      1152             4
1458     9717       1950          1996      1078         0             2
1459     9937       1965          1965      1256         0             3

      KitchenAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea
0                1             8           0         548
1                1             6           1         460
2                1             6           1         608
3                1             7           1         642
4                1             9           1         836
...            ...           ...         ...         ...
1455             1             7           1         460
1456             1             7           2         500
1457             1             9           2         252
1458             1             5           0         240
1459             1             6           0         276

[1460 rows x 10 columns]
The predictions are:
[208500. 181500. 223500. ... 266500. 142125. 147500.]

In [21]:
#To validate the quality of my model, I will use mean absolute error (MAE) to gain average of prediction errors within it
#To do this, I will split data into training and validation data to gain 'Out-of-sample' scores on error

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error as MAE

In [22]:
train_Z, val_Z, train_y, val_y = train_test_split (Z, y, random_state = 0)

In [23]:
iowa_model.fit(train_Z, train_y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=1, splitter='best')

In [24]:
#Calculating for MAE

val_predictions = iowa_model.predict(val_Z)
print (MAE(val_y, val_predictions))

31127.50684931507

In [25]:
#I would like to reduce this error defining it as 'smaller MAE'
#To do so, I will sort for underfitting or Overfitting by evaluating the depth of my decision tree
#I will therefore look for the maximum number of leaf nodes (MLN) to fit my data with the optimal tree depth

def smaller_mae(max_leaf_nodes, train_Z, val_Z, train_y, val_y):
    model = DTR(max_leaf_nodes = MLN, random_state = 0)
    model.fit(train_Z, train_y)
    preds_val = model.predict(val_Z)
    mae = MAE(val_y, preds_val)
    return (mae)

In [26]:
#Understanding that a very small tree depth leads to underfitting and a very large one leads to overfitting...
#...I will therefore compare different values of MLN to find optimal tree depth and assign it to 'best_mae'

for MLN in [5, 25, 50, 100, 250, 500, 750, 1000]:
    best_mae = smaller_mae(MLN, train_Z, val_Z, train_y, val_y)
    print ("MLN: %d \t\t MAE: %d" %(MLN, best_mae))

MLN: 5 		 MAE: 36453
MLN: 25 		 MAE: 26919
MLN: 50 		 MAE: 28687
MLN: 100 		 MAE: 27709
MLN: 250 		 MAE: 29721
MLN: 500 		 MAE: 29938
MLN: 750 		 MAE: 29940
MLN: 1000 		 MAE: 30020

In [27]:
#Optimal MLN is 25 with the lowest MAE of 26,919
#I will therefore fit my model with this MLN, assigning it to 'better iowa model'

better_iowa_model = DTR (max_leaf_nodes = 25, random_state = 0)
better_iowa_model.fit(train_Z, train_y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=25, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [28]:
preds_val = better_iowa_model.predict(val_Z)
print (MAE(val_y, preds_val))
print (better_iowa_model.predict(val_Z.head(1460)))

26919.331772581867
[244928.57142857 145000.         122553.97560976 161662.93043478
  93820.41891892 122553.97560976 282745.98571429 145000.
 690000.         188522.         221027.34       136607.10714286
 224358.02564103 122553.97560976 122553.97560976 136607.10714286
 221027.34       169990.34736842 136607.10714286 145000.
 122553.97560976 169990.34736842 122553.97560976 169990.34736842
 145000.         145000.         169990.34736842  93820.41891892
 282745.98571429 122553.97560976 136607.10714286 169990.34736842
 122553.97560976 282745.98571429 380208.75       169990.34736842
 221027.34       122553.97560976 224358.02564103 282745.98571429
 244928.57142857 161662.93043478 169990.34736842 282745.98571429
 282745.98571429 136607.10714286 122553.97560976 122553.97560976
 145000.         122553.97560976 496867.5        122553.97560976
 161662.93043478  93820.41891892 260759.32142857 122553.97560976
 145000.         282745.98571429 136607.10714286  93820.41891892
 122553.97560976 122553.97560976 161662.93043478 176035.48387097
 260759.32142857 161662.93043478 122553.97560976 188522.
 145000.         224358.02564103 169990.34736842 122553.97560976
 122553.97560976 221027.34       122553.97560976 282745.98571429
 122553.97560976  93820.41891892 278509.04545455 136607.10714286
 122553.97560976 122553.97560976 122553.97560976 188522.
 231571.         188522.          93820.41891892 221027.34
 169990.34736842 122553.97560976 188522.         145000.
 169990.34736842 224358.02564103 221027.34       161662.93043478
 188522.         231571.         122553.97560976 161662.93043478
 260759.32142857 224358.02564103 161662.93043478 145000.
  93820.41891892 278509.04545455 188522.         122553.97560976
 169990.34736842 145000.          93820.41891892 122553.97560976
 231571.          93820.41891892 188522.         145000.
 380208.75       122553.97560976 161662.93043478 282745.98571429
 169990.34736842 188522.         122553.97560976 161662.93043478
 260759.32142857 221027.34       380208.75       221027.34
 188522.         161662.93043478 282745.98571429 282745.98571429
 243315.5        161662.93043478 122553.97560976 260759.32142857
 122553.97560976 188522.         122553.97560976 188522.
 176035.48387097 188522.         244928.57142857 122553.97560976
 136607.10714286 169990.34736842 188522.         122553.97560976
 260759.32142857 221027.34       161662.93043478 282745.98571429
 282745.98571429 136607.10714286 145000.         243315.5
 136607.10714286 145000.         169990.34736842 169990.34736842
 122553.97560976 136607.10714286 188522.         122553.97560976
 282745.98571429 122553.97560976 161662.93043478 282745.98571429
 221027.34       169990.34736842 176035.48387097 145000.
 221027.34       221027.34       122553.97560976  93820.41891892
 136607.10714286 243315.5        122553.97560976 122553.97560976
 161662.93043478 161662.93043478  93820.41891892 282745.98571429
 122553.97560976 145000.          93820.41891892 188522.
 221027.34       169990.34736842 188522.         161662.93043478
 188522.         188522.         122553.97560976 122553.97560976
  93820.41891892 136607.10714286 145000.         145000.
 136607.10714286 221027.34        93820.41891892 122553.97560976
 145000.         243315.5        161662.93043478 282745.98571429
 282745.98571429 122553.97560976 188522.         260759.32142857
 122553.97560976  93820.41891892 244928.57142857 231571.
 161662.93043478 278509.04545455 282745.98571429  93820.41891892
 176035.48387097 161662.93043478 145000.         122553.97560976
 169990.34736842 282745.98571429 221027.34       244928.57142857
 161662.93043478 161662.93043478 122553.97560976  93820.41891892
 122553.97560976 169990.34736842 221027.34       145000.
 145000.         122553.97560976 136607.10714286 176035.48387097
  93820.41891892 221027.34       221027.34       221027.34
 161662.93043478 169990.34736842 161662.93043478 188522.
 122553.97560976 188522.         176035.48387097 282745.98571429
 122553.97560976 278509.04545455 188522.         260759.32142857
 122553.97560976 221027.34       362459.18181818 184750.
 188522.         145000.         145000.         145000.
 380208.75       260759.32142857 244928.57142857  93820.41891892
 145000.         282745.98571429 145000.         161662.93043478
 122553.97560976 176035.48387097 145000.         224358.02564103
 188522.         145000.         224358.02564103 122553.97560976
 122553.97560976 380208.75       145000.         122553.97560976
 221027.34       244928.57142857  93820.41891892 260759.32142857
 379523.6        161662.93043478  93820.41891892  93820.41891892
 282745.98571429 122553.97560976 122553.97560976 282745.98571429
 282745.98571429 169990.34736842 161662.93043478 188522.
  93820.41891892 122553.97560976 224358.02564103 169990.34736842
 145000.         161662.93043478 136607.10714286 176035.48387097
 169990.34736842 188522.         122553.97560976 188522.
 145000.         122553.97560976  93820.41891892 169990.34736842
 362459.18181818 136607.10714286 169990.34736842 161662.93043478
 122553.97560976 260759.32142857 122553.97560976 231571.
 145000.         221027.34       122553.97560976 282745.98571429
 176035.48387097 136607.10714286 122553.97560976 221027.34
 145000.         169990.34736842 161662.93043478 122553.97560976
 136607.10714286 221027.34       145000.         122553.97560976
 282745.98571429 169990.34736842 145000.         224358.02564103
 161662.93043478 145000.          93820.41891892 122553.97560976
 122553.97560976 122553.97560976 224358.02564103 362459.18181818
 122553.97560976 122553.97560976 188522.         380208.75
 282745.98571429 145000.         260759.32142857 231571.
 243315.5        161662.93043478 188522.         282745.98571429
  93820.41891892]

In [29]:
#From all I've learned, I think I can still reduce the MAE for better predictions
#To do this, I will use random forests of decision trees instead of just a singular decision tree
#A RandomForestRegressor should average predictions of each component tree within the forest

from sklearn.ensemble import RandomForestRegressor as RFR

In [30]:
rf_model = RFR(random_state = 0)
rf_model.fit(train_Z, train_y)

/home/braincreator/miniconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [31]:
iowa_preds = rf_model.predict(val_Z)
print (MAE(val_y, iowa_preds))
print (rf_model.predict(val_Z.head(1460)))

22619.05187214612
[242400.         134980.         117240.8        192690.
  93040.         120740.         255630.         127230.
 582845.4        177415.2        182423.5        170860.
 222380.         128240.         125962.5        140090.
 230850.         115200.         147067.5        142110.4
 119093.2        150750.         108348.3        167975.
 173285.         176198.7        177240.          84370.
 317550.         104750.         182622.5        185370.
 126600.         315395.         378369.3        178700.
 217435.         121250.         232785.6        274310.
 235700.         139983.7        185484.4        312570.
 293747.         159390.         131330.         123400.
 168665.         132400.         319001.5        148365.
 178983.7         93250.         252308.6        124900.
 140415.         243827.8        152930.          99840.
 140550.         122589.3        155040.         164545.
 256450.         150040.         124300.         208658.8
 144303.7        211530.         176491.7        120310.
  93327.9        201463.         122850.8        286459.6
 126325.8        110740.         286792.1        146980.
 143515.         132465.         109970.         164100.
 196147.         189053.2        125103.2        194829.
 185251.2        122290.         188200.         186495.
 178300.         241553.5        203607.8        152300.
 202977.8        167083.2        122700.         138640.
 238296.3        241134.3        142205.         151430.
 111150.         275122.5        158300.         108630.8
 174161.         132785.         115360.         124190.
 210040.         107500.         167740.         155500.
 429629.3        127280.         204260.         249959.8
 124370.         172738.         127500.         197140.
 221090.         208053.2        353904.5        215145.
 185880.         163070.         229989.9        219217.6
 181855.         184020.         124200.         267750.
 131440.         189603.2        129230.         192700.
 164400.         150290.         240850.         150840.
 142090.         177750.         206455.8        140640.
 260000.         233470.         159100.         269749.4
 321761.9        143930.         152630.         223530.
 122590.         169600.         102940.         170070.
 131550.         140960.         181510.         123375.
 258288.9        124635.         177640.         341500.
 192825.         178770.         192490.         168100.
 226856.1        195650.         124049.3        110500.
 130060.         245350.         100977.6        138686.4
 185930.         174390.          83350.         320387.2
 113489.3        170640.          86200.         195720.
 213931.9        142250.         163750.         151320.
 213100.         157140.         121867.6        151580.
  94330.         138350.         175980.         112900.
 142940.         185529.         125300.         104540.
 147030.         226200.         159590.         275920.
 331255.          74990.         154700.         251850.
  98390.          74930.         285040.         227795.
 175740.         255288.         239400.          77710.
 210750.         184200.         128033.4        125350.
 198026.4        280175.         200130.         260700.
 154313.7        163950.          96400.         125897.5
 102838.3        143850.         223322.5        119670.
 148280.         118750.         121145.         171597.
 100620.         209990.         207790.         223750.
 169523.7        154725.         211400.         186640.
 129340.         190935.         173140.         254110.
  90150.         318513.7        220530.         256400.
 104450.         231333.4        363002.3        487200.2
 183100.         153630.         158190.         109750.
 378710.3        305867.9        295970.          61055.5
 181180.         277967.7        131700.         187980.
 145985.         205900.         117990.         236032.3
 185930.         170538.7        214496.5         99855.
 129575.         378366.1        164190.         128650.
 209650.         181949.3        113100.         267940.
 388281.         188250.          59640.         114507.5
 333746.3        114690.8        119915.         302140.
 272075.         184408.5        157800.         167590.
  90840.         121500.         201208.5        178897.2
 165400.         143300.         136782.5        194700.
 169298.5        181760.         106830.         167881.46666667
 152190.         109187.6        115500.         140050.
 324489.         112750.         179662.2        190883.2
 117833.4        297790.         117140.         238390.
 138925.         227871.         134615.         342242.6
 198090.         136445.         126050.         225200.
 155240.         179265.1        173825.         168955.
 137620.         179450.         133300.         122939.3
 303720.2        158150.         142510.         214496.5
 165230.         146730.         124380.4         87547.2
 120750.         135600.         211700.         304700.
 113520.         125090.         190857.8        380995.6
 302205.         159920.         231190.         250587.
 253177.9        195800.         210100.         276672.4
  78940.        ]