In [1]:
import pandas as pd
import numpy as np
import os 
from sklearn.model_selection import train_test_split

In [4]:
pwd

'/home/braincreator'

In [5]:
#Capturing File Path
iowa_data_full = pd.read_csv('/home/braincreator/iowa/train.csv', index_col= 'Id')
iowa_data_test_full = pd.read_csv('/home/braincreator/iowa/test.csv', index_col='Id')

In [6]:
#Remove rows with missing target, separate target from predictions
iowa_data_full.dropna(axis=0, subset=['SalePrice'], inplace = True)
y = iowa_data_full.SalePrice
iowa_data_full.drop(['SalePrice'], axis=1, inplace = True)

In [7]:
iowa_data_full.describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
count,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,46.549315,...,472.980137,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753
std,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,161.319273,...,213.804841,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095
min,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000
25%,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,...,334.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000
50%,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,...,480.000000,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000
75%,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,0.000000,...,576.000000,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000
max,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,...,1418.000000,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000

In [8]:
iowa_data_full.head(5)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [9]:
iowa_data_full.shape[0]

1460

In [10]:
#Creating Train-Test Split
X_train_full, X_valid_full, y_train, y_valid = train_test_split(iowa_data_full, y, train_size = 0.8, test_size = 0.2,
                                                               random_state = 0)

In [11]:
#Selecting categorical columns with relatively low cardinality
categorical_lowcard_cols = [cname for cname in X_train_full.columns if 
                   X_train_full [cname].nunique()< 10 and
                   X_train_full[cname].dtype =='object']

#Selecting numerical columns
numerical_cols = [cname for cname in X_train_full.columns if
                  X_train_full[cname]. dtype in ['int64', 'float64']]

In [12]:
#Selected columns are now kept
my_cols = categorical_lowcard_cols + numerical_cols
X_train = X_train_full[my_cols].copy()
X_valid = X_valid_full[my_cols].copy()
X_test = iowa_data_test_full[my_cols].copy()

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error

In [14]:
#Preprocessing for numerical data
numerical_transformer = SimpleImputer(strategy = 'constant')

#Preprocessing for categorical data
categorical_transformer = Pipeline(steps = [('imputer', SimpleImputer(strategy='most_frequent')),
                                           ('onehot', OneHotEncoder(handle_unknown = 'ignore'))])

In [15]:
#Bundling preprocessing for numrical and categorical data
preprocessor = ColumnTransformer(transformers = [
    ('num', numerical_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_lowcard_cols)])

In [16]:
from sklearn.ensemble import RandomForestRegressor as RFR

#Fit with Pipeline model
my_pipeline = Pipeline(steps = [('preprocessor', preprocessor),
                                   ('model', RFR(n_estimators = 100, criterion = 'mae', random_state=0))])
my_pipeline.fit(X_train, y_train)
preds = my_pipeline.predict(X_valid)
mae = mean_absolute_error(y_valid, preds)

print ('MAE:', mae)

MAE: 17772.48205479452

In [18]:
print (my_pipeline.predict (X_valid.head(1460)))

[202317.84 145033.46 114737.5  235086.73  90438.   109400.05 257021.32
 124100.16 525460.56 155692.78 197873.81 147000.58 224241.25 117207.1
 126501.   147385.75 224312.91 119456.33 142949.   195880.7  131889.84
 142500.   119869.56 167893.27 181553.5  216187.48 165641.32  86589.
 327532.43 116924.37 135820.32 197716.4  144002.3  283061.08 323745.94
 183608.95 282831.7  128373.1  233644.52 311561.79 200437.4  130235.82
 179921.59 297565.64 324290.79 145003.39 130058.96 128402.5  165523.5
 103278.33 358502.55 144008.5  166122.5   90550.65 244440.74 115569.16
 136048.37 240562.99 141324.   105188.83 145218.   131388.58 144058.25
 149926.37 198881.   162074.5  126510.33 219989.03 123663.42 186239.57
 180609.74 122200.3   90595.65 221754.56  96046.58 259061.83 129249.
 109128.71 278136.79 159998.15 136915.6  127831.16 128056.57 142465.17
 182233.34 195702.26 104656.1  192203.05 173160.19 140050.33 190777.4
 187278.85 180143.5  225791.48 201789.36 151216.   211245.2  176424.56
 123405.82 142800.22 254117.83 236800.04 125716.45 158850.35 109281.72
 277194.4  153914.08 110986.45 176084.28 110359.28  94729.73 129843.
 199001.55 120593.8  167668.82 158084.35 419370.56 128182.93 186557.91
 255409.72 167469.69 168238.9  135036.8  213571.15 224900.16 223922.37
 391243.37 196171.52 209079.31 173168.46 228622.7  208759.83 137246.46
 184746.02 107218.31 234198.11 134201.71 187767.64 115380.29 180511.35
 140602.75 142238.5  202254.94 141527.87 146673.36 178074.82 225877.38
 139956.25 293616.68 240446.59 168832.85 370112.54 303546.17 154520.21
 179812.5  276155.38 122641.5  195056.5  122423.65 174321.04 126430.1
 148115.89 195820.48 129753.5  245134.9  122213.11 173005.86 279928.15
 188133.19 179352.9  166987.82 163234.57 181074.62 162899.5  124664.29
 109666.37 134781.5  219140.7  112793.5  147534.75 298650.87 215225.84
 109202.92 301932.11 119090.76 167691.5   97756.04 199391.52 197840.43
 140740.5  143144.09 157254.84 215377.2  128856.77 124340.93 145534.
  92689.6  135343.16 167478.9  132161.75 134117.39 197633.45 116877.26
 127542.09 138565.28 164796.37 150566.5  330309.54 253592.52  79297.
 155111.   256653.82  95561.58 103504.41 378354.33 212794.4  192047.1
 271508.21 248125.94  92291.5  220706.2  157165.28 130763.09 120323.33
 192804.75 265775.99 242654.61 208720.25 137984.37 166531.36  91714.
 166278.71 108151.3  142330.75 222180.4  122554.25 142978.85 123122.83
  90038.93 172347.16 115411.26 186669.1  200532.81 212257.63 169638.9
 187937.3  207045.97 188018.8  129675.   201963.66 175781.   258946.03
  93987.51 404999.75 222898.34 233737.11 101714.04 217442.32 397995.13
 464730.32 207227.73 132640.94 137883.54 103948.91 397398.02 319483.37
 329095.27  79186.97 228816.   242877.68 133892.03 232642.64 143215.09
 176342.34 129324.61 232986.88 227838.39 181451.35 218951.5  114704.5
 130873.13 388146.53 152516.11 142745.34 202094.37 158945.5  115269.92
 275369.66 446290.49 155589.87  81336.62  89825.82]

In [24]:
from sklearn.model_selection import cross_val_score as cvs

scores = -1 * cvs(my_pipeline, iowa_data_full, y,
                  cv=5,
                  scoring ='neg_mean_absolute_error')
                
print("Average MAE score:", scores.mean())

Average MAE score: 17762.528469178083

In [25]:
print ("MAE scores:\n", scores)

MAE scores:
 [17548.33049658 18098.57640411 18391.84503425 16241.65967466
 18532.2307363 ]

In [26]:
from sklearn.ensemble import RandomForestRegressor as RFR

#Fit with Pipeline model
my_pipeline = Pipeline(steps = [('preprocessor', preprocessor),
                                   ('model', RFR(n_estimators = 500, criterion = 'mae', random_state=0))])
my_pipeline.fit(X_train, y_train)
preds = my_pipeline.predict(X_valid)
mae = mean_absolute_error(y_valid, preds)

print ('MAE:', mae)

MAE: 17726.91469178082

In [27]:
from sklearn.model_selection import cross_val_score as cvs

scores = -1 * cvs(my_pipeline, iowa_data_full, y,
                  cv=5,
                  scoring ='neg_mean_absolute_error')
                
print("Average MAE score:", scores.mean())

Average MAE score: 17719.434823287673

In [28]:
#Getting predictions of test data with model
preds_test = my_pipeline.predict(iowa_data_test_full)
print (my_pipeline.predict(iowa_data_test_full.head(1460)))

[128079.394 153733.59  183684.532 ... 153862.502 110765.74  234966.004]